runtime: python37

service: chat-service

handlers:
- url: /.*
  script: auto

env_variables:
  CHAT_SERVICE_SQL_INSTANCE: 'talentexchange-236807:asia-east2:talent-chat-db-dev'
  CHAT_SERVICE_DB_NAME: 'chat_service'
  CHAT_SERVICE_DB_USER: 'talentAdmin'
  CHAT_SERVICE_DB_PASSWORD: 'Abcd1234'
