version: '3.1'

networks:
    user_net:

services:
           
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password 
        volumes:
            - ./script/create_table.sql:/data/application/init.sql
            - ~/datadrive/toolbox/user/mysql/:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: toolbox_user
        networks:
            - user_net
        
    app:
        build:
            dockerfile: Dockerfile
            context: ./
        image: toolbox-user-service:latest
        restart: always
        volumes:
            - ~/datadrive/toolbox/user/application/log/:/usr/src/app/log
        environment:
            PORT: 8080
            USER_SERVICE_SQL_INSTANCE: db
            USER_SERVICE_DB_USER: root
            USER_SERVICE_DB_PASSWORD: root
            USER_SERVICE_DB_NAME: toolbox_user
            DB_PORT: 3306
            JWT_SECRET_STRING: try-to-guess-the-secret
            WAIT_HOSTS: db:3306
        ports: 
            - 8080:8080
        networks:
            - user_net
        depends_on:
            - db
