version: '3.1'

networks:
    blog_net:

services:
           
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password 
        volumes:
            - ./script/create_table.sql:/data/application/init.sql
            - ~/datadrive/toolbox/blog/mysql/:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: abc123
          MYSQL_DATABASE: toolbox_blog
        networks:
            - blog_net
        
    app:
        build:
            dockerfile: Dockerfile
            context: ./
        image: toolbox-blog-service:latest
        restart: always
        volumes:
            - ~/datadrive/toolbox/blog/application/log/:/usr/src/app/log
        environment:
            PORT: 8081
            DB_HOST: db
            DB_USER: root
            DB_PASSWORD: abc123
            DB_DATABASE: toolbox_blog
            DB_PORT: 3306
            JWT_SECRET_STRING: try-to-guess-the-secret
            WAIT_HOSTS: db:3306
        ports: 
            - 8081:8081
        networks:
            - blog_net
        depends_on:
            - db
